# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: '' 
  group: default-app-group
  replicaCount: 1
  container: 
    image: add-image-here
    port: 8080 
    # Array of key-value pairs that will be injected into a container.
    # Example:
    # - key: DB_SERVER
    #   value: postgres
    # By default this is empty but it will be overrideen in each release of 
    # the application.
    env: []
  service:
    type: ClusterIP
    port: 8080
