apiVersion: apps/v1
kind: Deployment
metadata:
  # .Values is a built in Helm object which allows you to access the variables
  # defined in the values.yaml file in the Helm Chart
  name: {{ include "app.fullName" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.fullName" . }}
  template:
    metadata:
      labels:
{{ include "app.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ include "app.fullName" . }}
          image: {{ .Values.app.container.image }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          # Here we have to use the helm template function, range which will
          # take an array as a paramter and loop over it to give a generated
          # result.
          # In this case we are pulling in all of the environment variables
          # defined in the container.
          env: 
            {{- range .Values.app.container.env }}
            - name: {{ .key }}
              value: {{ .value }}
            {{- end }}
